from __future__ import annotations

import argparse
import json
import os
import re
import textwrap
import unicodedata
from datetime import date
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def slugify(value: str) -> str:
    value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    value = re.sub(r"[^a-zA-Z0-9]+", "-", value.lower()).strip("-")
    return value or "nacrt"


def facts_as_bullets(facts: dict) -> str:
    rows = []
    for key, value in facts.items():
        if key == "table":
            continue
        rows.append(f"- {key}: {value}")
    return "\n".join(rows)


def build_prompt(prompt_template: str, style_guide: str, facts: dict, title: str) -> tuple[str, str]:
    instructions = "\n\n".join(
        [
            prompt_template.strip(),
            "Stilske upute:",
            style_guide.strip(),
        ]
    )

    user_input = textwrap.dedent(
        f"""
        Napiši nacrt Quarto blog posta na hrvatskom.

        Naslov: {title}

        Provjerene činjenice:
        {facts_as_bullets(facts)}

        Ako činjenica nije navedena, nemoj je izmišljati. Za svaku brojku koristi samo gore navedene činjenice.
        Vrati samo Markdown/Quarto sadržaj, bez objašnjenja izvan posta.
        """
    ).strip()

    return instructions, user_input


def generate_with_openai(instructions: str, user_input: str) -> str:
    api_key = os.environ.get("OPENAI_API_KEY")
    model = os.environ.get("OPENAI_MODEL")

    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set.")
    if not model:
        raise RuntimeError("OPENAI_MODEL is not set.")

    try:
        from openai import OpenAI
    except ImportError as exc:
        raise RuntimeError("Install the Python package `openai` to generate drafts.") from exc

    client = OpenAI(api_key=api_key)
    response = client.responses.create(
        model=model,
        instructions=instructions,
        input=user_input,
        store=False,
    )
    return response.output_text


def offline_draft(title: str, facts: dict) -> str:
    today = date.today().isoformat()
    bullets = facts_as_bullets(facts)

    lines = [
        "---",
        f'title: "{title}"',
        f"date: {today}",
        "categories: []",
        'description: ""',
        "draft: true",
        "---",
        "",
        "## Sažetak",
        "",
        "TODO: Napiši kratak sažetak na temelju provjerenih činjenica.",
        "",
        "## Podaci i metodologija",
        "",
        "Korištene provjerene činjenice:",
        "",
        bullets,
        "",
        "## Rezultati",
        "",
        "TODO: Ovdje opiši rezultate bez dodavanja brojki koje nisu navedene u facts datoteci.",
        "",
        "## Interpretacija",
        "",
        "TODO: Razdvoji nalaz, moguću interpretaciju i ograničenja.",
        "",
        "## Ograničenja",
        "",
        "TODO: Navedi što se iz ovih podataka ne može zaključiti.",
        "",
        "## Izvori",
        "",
        "TODO: Navedi GFI, Eurostat ili drugi izvor i datum preuzimanja.",
    ]
    return "\n".join(lines) + "\n"


def default_output_path(title: str) -> Path:
    return PROJECT_ROOT / "drafts" / "ai" / f"{date.today().isoformat()}-{slugify(title)}.qmd"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a AI.econ AI-assisted draft.")
    parser.add_argument(
        "--facts",
        type=Path,
        default=PROJECT_ROOT / "outputs" / "facts" / "example_facts.json",
        help="Path to facts JSON generated by an analysis script.",
    )
    parser.add_argument("--title", default=None, help="Draft title. Defaults to title from facts.")
    parser.add_argument(
        "--prompt",
        type=Path,
        default=PROJECT_ROOT / "prompts" / "croaicon_post_prompt.md",
    )
    parser.add_argument(
        "--style",
        type=Path,
        default=PROJECT_ROOT / "prompts" / "style_guide_hr.md",
    )
    parser.add_argument("--out", type=Path, default=None, help="Output .qmd draft path.")
    parser.add_argument("--offline", action="store_true", help="Write a structured draft without API calls.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    facts = read_json(args.facts)
    title = args.title or facts.get("title", "AI.econ nacrt")
    output = args.out or default_output_path(title)
    output.parent.mkdir(parents=True, exist_ok=True)

    if args.offline:
        draft = offline_draft(title, facts)
    else:
        instructions, user_input = build_prompt(read_text(args.prompt), read_text(args.style), facts, title)
        try:
            draft = generate_with_openai(instructions, user_input)
        except RuntimeError as exc:
            draft = offline_draft(title, facts)
            draft += f"\n<!-- AI generation skipped: {exc} -->\n"

    output.write_text(draft, encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
